backend:
  name: git-gateway
  branch: master
media_folder: "public/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: 'vid'
    label: 'video'
    folder: 'src/products/vid'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string", default: "vid" }